title: Dominic Chong
name: Dominic Chong
email: dominicchongjh@gmail.com
description: Unity/UE4 Game Developer<br><br>Computer Science Undergraduate at National University of Singapore

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

remote_theme: jekyll-material-theme

parallax_image_one: /assets/images/tember-defense.png # These are the images used for the parallax background
parallax_image_two: /assets/images/tember-defense.png

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "Tember Defense"
project_one_description:
- "A Tower Defense game with RTS elements.<br>Solo project made in Unity.<br><br>
- Tember Defense features modular systems, that can be composed together to form new and interesting gameplay mechanics.<br>
- The heavy usage of ScriptableObjects makes the game extremely designer-friendly, as all changes can be done in the editor and stored in assets that are not prefabs.
- ScriptableObjects, like Effects and Monsters, can also be reused in multiple occassions, making balance changes easier to be kept consistent.<br>
- The way that features such as Effects, Skill, Projectile Behaviour, Units, and Buildings
- are well-defined from one another makes the code easy to customize and even extend, eg. adding a new  effect.<br><br>"
project_one_url: https://glazed.itch.io/tember-defense #maybe lead to a separate post itself
project_one_icon: tember-defense
project_one_button: itch.io

project_two: "The Dots (Working prototype)"
project_two_description: "The Dots is a high score reflex game made for the mobile platform,
which has simple game play mechanics and extensive customization options for the player's avatar.<br><br>
Solo project made in Unity. Playable WebGL build on itch.io.<br>
Currently in development for its eventual full release. <br><br>
One of the main pillars when starting this mobile game project was to focus on simplicity in game design,
as I wanted to practice on developing game feel such as the usage of Particle Systems and Sound in Unity.<br><br>
Trivia: The game's first playable prototype was done in less than a day."
project_two_url: https://glazed.itch.io/the-dots
project_two_icon: the-dots


project_three: The Shifter
project_three_description: "
The Shifter was made during Gamecraft 2017, a 24 hour game jam held in Singapore.<br>
'Shift' was the theme of the game jam. <br><br>
Made in Unity.<br>
Sophia Simangam: Art and Level Design<br>
Dominic Chong: Programming and Game Design<br>"
project_three_url: https://glazed.itch.io/the-shifter
project_three_icon: shifter


project_four: Who are You?
project_four_description: "
A minimalistic personality exploration game made during NUS' Hack And Roll 2018.<br>
Made in Unity in 24 hours.<br>
Sophia Simangam: Game and Level design<br>
Dominic Chong: Programming & Game Design<br>"
project_four_url: https://glazed.itch.io/who-are-you
project_four_icon: who-are-you

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: c
  - name: cplusplus
  - name: csharp
  - name: java
  - name: python
  - name: git
  - name: gitlab
  - name: bitbucket
  - name: sourcetree
    uri: /assets/images/unity.jpg # Add external icon, for internal icon use uri: /assets/my_icon.jpg
    uri: /assets/images/ue4.png

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: https://bannified.github.io/gh-pages-test/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
