title: Dominic Chong
name: Dominic Chong
email: dominicchongjh@gmail.com
description: Unity/UE4 Game Developer<br><br>Computer Science Undergraduate at National University of Singapore

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

remote_theme: jekyll-material-theme

parallax_image_one: /assets/images/tember-defense.png # These are the images used for the parallax background
parallax_image_two: /assets/images/tember-defense.png

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "Tember Defense"
project_one_description: >
A Tower Defense game with RTS elements.<br>Solo project made in Unity.<br><br>
Tember Features features modular systems, that can be composed together to form new and interesting gameplay mechanics.
The heavy usage of ScriptableObjects makes game balance extremely friendly for game designers to tweak values.
project_one_url: https://glazed.itch.io/tember-defense #maybe lead to a separate post itself
project_one_icon: tember-defense
project_one_button: itch.io

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: c
  - name: cplusplus
  - name: csharp
  - name: java
  - name: python
  - name: git
  - name: gitlab
  - name: bitbucket
  - name: sourcetree
    uri: https://www.brandeps.com/logo-download/U/Unity-Game-Engine-01.png # Add external icon, for internal icon use uri: /assets/my_icon.jpg
    uri: https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Unreal_Engine_4_logo_and_wordmark.svg/512px-Unreal_Engine_4_logo_and_wordmark.svg.png

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: https://bannified.github.io/gh-pages-test/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
